---
- name: configure_firewall | Enable firewalld
  service:
    state: started
    enabled: yes
    name: firewalld
  tags:
    - firewall

- name: configure_firewall | Configuring firewalld services
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - RH-Satellite-6
    - tftp
    - dns
    - dhcp
  tags:
    - firewall

- name: configure_firewall | Open firewall port for ocp container registry
  firewalld:
    port: 5000/tcp
    permanent: true
    state: enabled
    immediate: true
  tags:
    - firewall

- name: configure_firewall | Restart firewalld
  service:
    name: firewalld
    state: restarted
  tags:
    - firewall
